package controller;

public enum MenuTypes {
    SIGNUPCONTROLLER,
    LOGINCONTROLLER,
    BEFOREGAMECONTROLLER,
    MAINCONTROLLER,
    CHANGEPASSWORDCONTROLLER,
    SCOREBOARDCONTROLLER,
    CHOOSEMAZECONTROLLER,
    FAVORITEMAZECONTROLLER

}
